name: Bug Report
description: If you think you've found a bug in the software
title: ":cockroach: <TITLE>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking your time to fill out this bug report

        We're sorry you're experiencing an issue. So that we can help you effectively, please fill in this form to the best of your ability.

        **Helpful Links**
        - [Code of Conduct](https://github.com/twitch-choke/.github/blob/main/CODE_OF_CONDUCT.md)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agreed to the project's [Code of Conduct](https://github.com/twitch-choke/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide clearly ordered steps to reproduce the issue
      placeholder: |
        1. Login to Twitch
        2. Click Cancel
        3. ALT + F4
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else?
      description: Anything else that we should know about your issue?
      placeholder: |
        eg: System Information, Version Information
    validations:
      required: false
